### ISSUE TITLE
Provide build instructions

### ISSUE THREAD

**Issue by keith-turner** [ohdatboi/ecoji-d#1]
If its easy to provide, build instructions in the readme that explain how to go from source to an executable would be really nice.  Below is an example of what I provided for Go.

https://github.com/keith-turner/ecoji/tree/c61775759e54d49d80aaca698315932f9267f4b6#build-instructions

**Comment by AntonMeep** [comment]
No "building" is required, it is done by dub automatically. I added  links to the D compiler and dub download pages so it'll be clear.
